import Head from "next/head";
import Navbar from "@/components/Navbar/TopNavbar";

// styles
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import MidNav from "@/components/Navbar/MidNav";
import FlightDetails from "@/components/RadioBtn/RadioBtn";
import BookingDatesComp from "@/components/BookingDatesComp/BookingDatesComp";
import FairType from "@/components/FairType/FairType";
import SearchBtn from "@/components/Buttons/SearchBtn";

// ? redux setup
// import { useSelector, useDispatch } from "react-redux";
// import { decrement, increment } from "../redux/stateSlice";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // ? redux setup
  // const count = useSelector((state) => state.counter.value);
  // const dispatch = useDispatch();
  return (
    <>
      <Head>
        <title>Next trip</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mainContainer">
        <div className={styles.main}>
          <Navbar />
          <MidNav />
          <div className={`${styles.centerComp} mb-5`}>
            <div className="flex justify-between">
              <div className="flex">
                <FlightDetails />
              </div>
              <div className="flex items-center text-sm pe-5">
                Book International and Domestic Flights
              </div>
            </div>

            <div className={`flex ${styles.bookingDates}`}>
              <BookingDatesComp
                title={"From"}
                body={"Chennai"}
                footer={"MAA, Chennai International Airport India"}
              />
              <BookingDatesComp
                title={"To"}
                body={"Goa"}
                footer={"GOI, Goa Dabolim International Airport India"}
              />
              <BookingDatesComp
                title={"Departure"}
                body={"1 Apr'24 "}
                footer={"Sunday"}
              />
              <BookingDatesComp
                title={"Return"}
                body={""}
                footer={"Tap to add a return date for bigger discounts"}
              />
              <BookingDatesComp
                title={"Travellers & Class"}
                body={"1 Traveller"}
                footer={"Economy/Premium Economy"}
              />
            </div>
            <FairType />
          </div>
          <SearchBtn />
        </div>
      </main>
    </>
  );
}
